
GET http://127.0.0.1:8000/
Content-Type: application/json

###
GET http://127.0.0.1:8000/category/1/
Content-Type: application/json

###
GET http://127.0.0.1:8000/user/1/
Content-Type: application/json

###
GET http://127.0.0.1:8000/user/4/category/2/
Content-Type: application/json

###

POST http://127.0.0.1:8000/signup/
Content-Type: application/json

{"username":"albertWily","password":"yellowDevil", "email":"bad@gmail.com"}

###
POST http://127.0.0.1:8000/login/
Content-Type:application/json


{"username":"albertWily","password":"yellowDevil"}


### token must be changed manuall, same goes with stuff lie transactions id

GET http://127.0.0.1:8000/test_token 
Content-Type:  application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2ODc0NTMwLCJpYXQiOjE3MzY4NzA5MzAsImp0aSI6IjA2MTVjYTEwNDkwMzQ5ODY4ZTQxYmFjYzE1ZmE1ZDcwIiwidXNlcl9pZCI6MTF9.mb7zobbAWSNMMnPV4auDQ14Jsi1DKDDhVCAZRc9tiAc

{}
###
POST http://127.0.0.1:8000/postAddress/
Content-Type: application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2ODc5NzQ5LCJpYXQiOjE3MzY4NzYxNDksImp0aSI6IjQ2ODdhNjg5ZjExNDQ1Mzk5ZmEyZjMwMzQ5MDFhNTFmIiwidXNlcl9pZCI6MTF9.2azsOUOMoM2-aor_mnSSL3zRsjUMyYC5m1EF5VELEmQ


{"country":"Poland","town":"wroclaw","street":"szkolna","postal_code":57123,"building_number":4}


###
GET http://127.0.0.1:8000/user/10/addresses/
Content-Type:  application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1ODk5NTk0LCJpYXQiOjE3MzU4OTkyOTQsImp0aSI6IjczYzVhMDRjYjJjMjRlYjM5NjUwMDYyZDI3OTA4MjUxIiwidXNlcl9pZCI6MTF9.Alc51Fs6LFFe8rEP8nn_BVmYMpywtk41yk0o9Lp3OpU

{}


###
POST http://127.0.0.1:8000/transactions/
Content-Type: application/json
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1ODk5NTk0LCJpYXQiOjE3MzU4OTkyOTQsImp0aSI6IjczYzVhMDRjYjJjMjRlYjM5NjUwMDYyZDI3OTA4MjUxIiwidXNlcl9pZCI6MTF9.Alc51Fs6LFFe8rEP8nn_BVmYMpywtk41yk0o9Lp3OpU

{"listing":2}
### 314bdeedf9730c7c9cce29eb3617ca5c23ecfbc5 the token is old, all of them are, because they will change after an hour. so it requieres manual change for testing

PATCH http://127.0.0.1:8000/transactions/16/update/
Content-Type: application/json
Authorization: Bearer  314bdeedf9730c7c9cce29eb3617ca5c23ecfbc5

{"status":"completed"}

###
PATCH http://127.0.0.1:8000/transactions/17/update/
Content-Type: application/json
Authorization: Bearer  314bdeedf9730c7c9cce29eb3617ca5c23ecfbc5

{"status":"cancelled"}