# Generated by Django 4.2.17 on 2024-12-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('bought', 'Bought'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='active', max_length=10),
        ),
    ]
